// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	models "next-german-words/app/store/models"

	mock "github.com/stretchr/testify/mock"
)

// Translator is an autogenerated mock type for the Translator type
type Translator struct {
	mock.Mock
}

// GetRandomWord provides a mock function with given fields: wordsToFilter
func (_m *Translator) GetRandomWord(wordsToFilter *[]string) *models.Word {
	ret := _m.Called(wordsToFilter)

	var r0 *models.Word
	if rf, ok := ret.Get(0).(func(*[]string) *models.Word); ok {
		r0 = rf(wordsToFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Word)
		}
	}

	return r0
}

// RefreshWords provides a mock function with given fields:
func (_m *Translator) RefreshWords() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TranslateWord provides a mock function with given fields: word
func (_m *Translator) TranslateWord(word string) (*models.Word, error) {
	ret := _m.Called(word)

	var r0 *models.Word
	if rf, ok := ret.Get(0).(func(string) *models.Word); ok {
		r0 = rf(word)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Word)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(word)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
