version: "3.7"

services:
  app:
    build: .
    restart: "no"
    depends_on:
      - mongodb
    networks:
      - app-network
    env_file:
      - .dockerenv
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ogg
    env_file:
      - .dockerenv
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./oggData:/data/db
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge