version: 3

tasks:
  test:
    cmds:
      - go test -v ./...
  mongo:
    cmds:
      - docker-compose up -d mongodb
  run:
    cmds:
      - go run app/main.go
  docker-build:
    cmds:
      - docker build -t docker.pkg.github.com/sonac/ogg/ogg .
