// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	models "next-german-words/app/store/models"

	mock "github.com/stretchr/testify/mock"
)

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

// GetWords provides a mock function with given fields:
func (_m *Database) GetWords() ([]*models.Word, error) {
	ret := _m.Called()

	var r0 []*models.Word
	if rf, ok := ret.Get(0).(func() []*models.Word); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Word)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
